---
- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
    gcp_project: tensile-imprint-271321
    gcp_cred_kind: serviceaccount
    gcp_cred_file: /home/guerlielton/credentials/gcp/credential.json
    zone: "us-central1-a"
    region: "us-central1"
    name_instance: web-server
  tasks:
    - name: Create a disk
      gcp_compute_disk:
        name: "{{ name_instance }}"
        size_gb: 10
        source_image: "projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts"
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: disk

    - name: Create a VPC network
      gcp_compute_network:
        name: "default"
        auto_create_subnetworks: "true"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: network

    - name: Create a firewall
      gcp_compute_firewall:
        name: "{{ name_instance }}"
        network: "{{ network }}"
        allowed:
          - ip_protocol: tcp
            ports: ["80"]
        # Firewall tag for match tag instance
        target_tags:
          - web-server
        source_ranges: ["0.0.0.0/0"]
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: firewall

    - name: Create an IPv4 Public IP address
      gcp_compute_address:
        name: "{{ name_instance }}"
        address_type: "EXTERNAL"
        network_tier: "PREMIUM"
        region: "{{ region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: address

    - name: Create a instance Web Server
      gcp_compute_instance:
        state: present
        name: "{{ name_instance }}"
        machine_type: g1-small
        disks:
          - auto_delete: true
            boot: true
            source: "{{ disk }}"
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: "External NAT"
                nat_ip: "{{ address }}"
                type: "ONE_TO_ONE_NAT"
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        # Network tag for traffic inbound exclusive instance
        tags:
          items:
            - web-server
      register: instance

    - name: Show Details Instance
      debug:
        msg: "The instance is accessible at {{ address.address }}"

    - name: Wait for SSH to come up.
      wait_for: host={{ address.address }} port=22 delay=10 timeout=60
