---
- hosts: web-server
  gather_facts: no
  # Become define scale privileges root
  become: yes
  tasks:
    - name: Install Docker
      shell: curl -fsSL https://get.docker.com | bash -

    - name: Docker Pull Image From Docker Hub
      shell: docker pull guerlielton/devops-challenge

    - name: Docker Run Container
      #Port 80 the host docker and port 3000 the docker container.
      shell: docker run -p 80:3000 -d guerlielton/devops-challenge
